version: "3.7"

services:
  docker-mysql:
   container_name: docker-mysql
   image: mysql:5.7
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3307:3306"
