version: "3.7"

services:
  docker-mysql:
   container_name: docker-mysql
   image: mysql:5.7
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: root
    MYSQL_ROOT_HOST: '%'
   volumes:
      - my-db:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
   ports:
   - "3307:3306"

volumes:
  my-db:
   name: my-db
  
